name: compliance

on:
  push:
    branches: ['main']
    paths:
      - 'src'
      - '.github'
      - 'package.json'
      - 'bun.lockb'
      - 'tailwind.config.js'
      - 'next.config.mjs'
      - 'tsconfig.json'
      - 'vercel.json'
      - 'trigger.config.ts'
      - 'postcss.config.mjs'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  license:
    name: FOSSA Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}-

      - name: install deps
        run: bun i --frozen-lockfile

      - name: Build
        run: bun run build

      - name: FOSSA Scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

      - name: FOSSA Tests
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
